//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservices.nbgz.me
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoModelInput", Namespace="http://tempuri.org/")]
    internal partial class PedidoModelInput : object
    {
        
        private Webservices.nbgz.me.Producto[] ProductosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal Webservices.nbgz.me.Producto[] Productos
        {
            get
            {
                return this.ProductosField;
            }
            set
            {
                this.ProductosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://tempuri.org/")]
    internal partial class Producto : object
    {
        
        private string NombreProductoField;
        
        private decimal PrecioUnitarioField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string NombreProducto
        {
            get
            {
                return this.NombreProductoField;
            }
            set
            {
                this.NombreProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal decimal PrecioUnitario
        {
            get
            {
                return this.PrecioUnitarioField;
            }
            set
            {
                this.PrecioUnitarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        internal int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoModelResponse", Namespace="http://tempuri.org/")]
    internal partial class PedidoModelResponse : object
    {
        
        private decimal ImpuestosField;
        
        private decimal SubTotalField;
        
        private decimal TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal decimal Impuestos
        {
            get
            {
                return this.ImpuestosField;
            }
            set
            {
                this.ImpuestosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal decimal SubTotal
        {
            get
            {
                return this.SubTotalField;
            }
            set
            {
                this.SubTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal decimal Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Webservices.nbgz.me.IServices")]
    internal interface IServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/EnviarMensaje", ReplyAction="*")]
        System.Threading.Tasks.Task<Webservices.nbgz.me.EnviarMensajeResponse> EnviarMensajeAsync(Webservices.nbgz.me.EnviarMensajeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServices/CalcularPedido", ReplyAction="*")]
        System.Threading.Tasks.Task<Webservices.nbgz.me.CalcularPedidoResponse> CalcularPedidoAsync(Webservices.nbgz.me.CalcularPedidoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class EnviarMensajeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarMensaje", Namespace="http://tempuri.org/", Order=0)]
        public Webservices.nbgz.me.EnviarMensajeRequestBody Body;
        
        public EnviarMensajeRequest()
        {
        }
        
        public EnviarMensajeRequest(Webservices.nbgz.me.EnviarMensajeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class EnviarMensajeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensaje;
        
        public EnviarMensajeRequestBody()
        {
        }
        
        public EnviarMensajeRequestBody(string mensaje)
        {
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class EnviarMensajeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarMensajeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Webservices.nbgz.me.EnviarMensajeResponseBody Body;
        
        public EnviarMensajeResponse()
        {
        }
        
        public EnviarMensajeResponse(Webservices.nbgz.me.EnviarMensajeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class EnviarMensajeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviarMensajeResult;
        
        public EnviarMensajeResponseBody()
        {
        }
        
        public EnviarMensajeResponseBody(string EnviarMensajeResult)
        {
            this.EnviarMensajeResult = EnviarMensajeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class CalcularPedidoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularPedido", Namespace="http://tempuri.org/", Order=0)]
        public Webservices.nbgz.me.CalcularPedidoRequestBody Body;
        
        public CalcularPedidoRequest()
        {
        }
        
        public CalcularPedidoRequest(Webservices.nbgz.me.CalcularPedidoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class CalcularPedidoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Webservices.nbgz.me.PedidoModelInput inputModel;
        
        public CalcularPedidoRequestBody()
        {
        }
        
        public CalcularPedidoRequestBody(Webservices.nbgz.me.PedidoModelInput inputModel)
        {
            this.inputModel = inputModel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class CalcularPedidoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularPedidoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Webservices.nbgz.me.CalcularPedidoResponseBody Body;
        
        public CalcularPedidoResponse()
        {
        }
        
        public CalcularPedidoResponse(Webservices.nbgz.me.CalcularPedidoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class CalcularPedidoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Webservices.nbgz.me.PedidoModelResponse CalcularPedidoResult;
        
        public CalcularPedidoResponseBody()
        {
        }
        
        public CalcularPedidoResponseBody(Webservices.nbgz.me.PedidoModelResponse CalcularPedidoResult)
        {
            this.CalcularPedidoResult = CalcularPedidoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    internal interface IServicesChannel : Webservices.nbgz.me.IServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    internal partial class ServicesClient : System.ServiceModel.ClientBase<Webservices.nbgz.me.IServices>, Webservices.nbgz.me.IServices
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicesClient() : 
                base(ServicesClient.GetDefaultBinding(), ServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicesClient.GetBindingForEndpoint(endpointConfiguration), ServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Webservices.nbgz.me.EnviarMensajeResponse> Webservices.nbgz.me.IServices.EnviarMensajeAsync(Webservices.nbgz.me.EnviarMensajeRequest request)
        {
            return base.Channel.EnviarMensajeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Webservices.nbgz.me.EnviarMensajeResponse> EnviarMensajeAsync(string mensaje)
        {
            Webservices.nbgz.me.EnviarMensajeRequest inValue = new Webservices.nbgz.me.EnviarMensajeRequest();
            inValue.Body = new Webservices.nbgz.me.EnviarMensajeRequestBody();
            inValue.Body.mensaje = mensaje;
            return ((Webservices.nbgz.me.IServices)(this)).EnviarMensajeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Webservices.nbgz.me.CalcularPedidoResponse> Webservices.nbgz.me.IServices.CalcularPedidoAsync(Webservices.nbgz.me.CalcularPedidoRequest request)
        {
            return base.Channel.CalcularPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Webservices.nbgz.me.CalcularPedidoResponse> CalcularPedidoAsync(Webservices.nbgz.me.PedidoModelInput inputModel)
        {
            Webservices.nbgz.me.CalcularPedidoRequest inValue = new Webservices.nbgz.me.CalcularPedidoRequest();
            inValue.Body = new Webservices.nbgz.me.CalcularPedidoRequestBody();
            inValue.Body.inputModel = inputModel;
            return ((Webservices.nbgz.me.IServices)(this)).CalcularPedidoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServices))
            {
                return new System.ServiceModel.EndpointAddress("http://webservices.nbgz.me/Services.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServices,
        }
    }
}
